services:
  frankenphp:
    container_name: app
    image: dunglas/frankenphp
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - ${HTTPS_PORT:-443}:443
      - ${HTTPS_PORT:-443}:443/udp
    environment:
      TZ: Europe/Copenhagen
      SERVER_NAME: ${SERVER_NAME:-localhost}
      FRANKENPHP_CONFIG: ${FRANKENPHP_CONFIG}
